name: Swiss Army Plugin
main: com.gmail.mpaul0416.SwissArmyPlugin.SwissArmyPlugin
version: 1.1.3
commands:
  lumberjack:
    description: Toggle the auto-lumberjack mode.
    usage: usage /lumberjack [on|off|status] - Turns your auto-lumberjackering on, off, or checks your status
    permission: SwissArmyPlugin.basic
    permission-message: You don't have permission to be an auto-lumberjack!
  farmer:
    description: Toggle the auto-farmer mode.
    usage: usage /farmer [on|off|status] - Turns on/off or checks status of auto-farmer
    permission: SwissArmyPlugin.basic
    permission-message: You don't have permission to be an auto-farmer!
